.TH hr 1 "2022-09-14" "hr"

.SH NAME
hr \- A horizontal rule for terminal

.SH SYNOPSIS
\fBhr\fR [\fB-h\fR] [\fB-v\fR] [\fB-n\fR \fICOUNT\fR] [\fB-l\fR] [\fB-r\fR] [\fICHAR\fR]

.SH DESCRIPTION
A tool that prints a horizontal rule, like the HTML <hr> tag, to your terminal. \fBhr\fR is particularly useful for distinguishing the output when running multiple commands.

.SH OPTIONS

.IP "\fB-h\fR"
Display the help message and exit

.IP "\fB-v\fR"
Display the version number of hr and exit

.IP "\fB-n\fR \fICOUNT\fR"
Repeat \fICHAR\fR \fICOUNT\fR times

.IP "\fB-l\fR"
Left alignment

.IP "\fB-r\fR"
Right alignment

.SH AUTHOR
Gustavo Costa <xfgusta@gmail.com>

.SH BUGS
Report bugs to <https://github.com/xfgusta/hr/issues>

.SH COPYRIGHT
Copyright (c) 2022 Gustavo Costa
